// Generated by Harpia. Do not edit.
package com.example.customer.web;

import com.example.customer.dto.CustomerResponse;
import com.example.customer.error.NotFoundException;
import com.example.customer.service.CustomerService;
import java.util.List;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import org.mockito.ArgumentMatchers;
import org.mockito.Mockito;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.request.MockMvcRequestBuilders;
import org.springframework.test.web.servlet.result.MockMvcResultMatchers;

/**
 * Every endpoint declared for Customer, and every failure it declares.
 */
@WebMvcTest(CustomerController.class)
class CustomerControllerTest {

    private static final UUID ID = UUID.fromString("00000000-0000-0000-0000-000000000001");

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private CustomerService service;

    @Test
    void createCustomerReturnsItsDeclaredStatus() throws Exception {
        Mockito.when(service.createCustomer(ArgumentMatchers.any()))
                .thenReturn(sampleResponse());

        mockMvc.perform(MockMvcRequestBuilders.post("/customers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"name\":\"name\",\"email\":\"email@example.com\"}"))
                .andExpect(MockMvcResultMatchers.status().is(201));
    }

    @Test
    void createCustomerRejectsAnIncompleteBody() throws Exception {
        mockMvc.perform(MockMvcRequestBuilders.post("/customers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(MockMvcResultMatchers.status().is(400));
    }

    @Test
    void createCustomerReportsADuplicate() throws Exception {
        DataIntegrityViolationException conflict =
                new DataIntegrityViolationException(
                        "duplicate key value violates unique constraint \"uq_customer_email\"");
        Mockito.when(service.createCustomer(ArgumentMatchers.any())).thenThrow(conflict);

        mockMvc.perform(MockMvcRequestBuilders.post("/customers")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"name\":\"name\",\"email\":\"email@example.com\"}"))
                .andExpect(MockMvcResultMatchers.status().is(409))
                .andExpect(MockMvcResultMatchers.jsonPath("$.message").value("email already exists"));
    }

    @Test
    void getCustomerReturnsItsDeclaredStatus() throws Exception {
        Mockito.when(service.getCustomer(ArgumentMatchers.any()))
                .thenReturn(sampleResponse());

        mockMvc.perform(MockMvcRequestBuilders.get("/customers/{id}", ID))
                .andExpect(MockMvcResultMatchers.status().is(200));
    }

    @Test
    void getCustomerReportsAMissingRecord() throws Exception {
        Mockito.when(service.getCustomer(ArgumentMatchers.any())).thenThrow(new NotFoundException("Customer", ID));

        mockMvc.perform(MockMvcRequestBuilders.get("/customers/{id}", ID))
                .andExpect(MockMvcResultMatchers.status().is(404));
    }

    @Test
    void listCustomersReturnsItsDeclaredStatus() throws Exception {
        Mockito.when(service.listCustomers())
                .thenReturn(List.of(sampleResponse()));

        mockMvc.perform(MockMvcRequestBuilders.get("/customers"))
                .andExpect(MockMvcResultMatchers.status().is(200));
    }

    @Test
    void updateCustomerReturnsItsDeclaredStatus() throws Exception {
        Mockito.when(service.updateCustomer(ArgumentMatchers.any(), ArgumentMatchers.any()))
                .thenReturn(sampleResponse());

        mockMvc.perform(MockMvcRequestBuilders.put("/customers/{id}", ID)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"name\":\"name\",\"email\":\"email@example.com\",\"active\":true}"))
                .andExpect(MockMvcResultMatchers.status().is(200));
    }

    @Test
    void updateCustomerRejectsAnIncompleteBody() throws Exception {
        mockMvc.perform(MockMvcRequestBuilders.put("/customers/{id}", ID)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{}"))
                .andExpect(MockMvcResultMatchers.status().is(400));
    }

    @Test
    void updateCustomerReportsAMissingRecord() throws Exception {
        Mockito.when(service.updateCustomer(ArgumentMatchers.any(), ArgumentMatchers.any())).thenThrow(new NotFoundException("Customer", ID));

        mockMvc.perform(MockMvcRequestBuilders.put("/customers/{id}", ID)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"name\":\"name\",\"email\":\"email@example.com\",\"active\":true}"))
                .andExpect(MockMvcResultMatchers.status().is(404));
    }

    @Test
    void updateCustomerReportsADuplicate() throws Exception {
        DataIntegrityViolationException conflict =
                new DataIntegrityViolationException(
                        "duplicate key value violates unique constraint \"uq_customer_email\"");
        Mockito.when(service.updateCustomer(ArgumentMatchers.any(), ArgumentMatchers.any())).thenThrow(conflict);

        mockMvc.perform(MockMvcRequestBuilders.put("/customers/{id}", ID)
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("{\"name\":\"name\",\"email\":\"email@example.com\",\"active\":true}"))
                .andExpect(MockMvcResultMatchers.status().is(409))
                .andExpect(MockMvcResultMatchers.jsonPath("$.message").value("email already exists"));
    }

    @Test
    void deleteCustomerReturnsItsDeclaredStatus() throws Exception {

        mockMvc.perform(MockMvcRequestBuilders.delete("/customers/{id}", ID))
                .andExpect(MockMvcResultMatchers.status().is(204));
    }

    @Test
    void deleteCustomerReportsAMissingRecord() throws Exception {
        Mockito.doThrow(new NotFoundException("Customer", ID)).when(service).deleteCustomer(ArgumentMatchers.any());

        mockMvc.perform(MockMvcRequestBuilders.delete("/customers/{id}", ID))
                .andExpect(MockMvcResultMatchers.status().is(404));
    }

    private static CustomerResponse sampleResponse() {
        return new CustomerResponse(UUID.fromString("00000000-0000-0000-0000-000000000001"), "name", "email@example.com", true);
    }
}
