package dev.harpia.emit;

/** Stable generated-file markers. They intentionally contain no version, host, or timestamp. */
public final class GeneratedHeader {

    private static final String MESSAGE = "Generated by Harpia. Do not edit.";

    private GeneratedHeader() {
    }

    public static String javaComment() {
        return "// " + MESSAGE;
    }

    public static String xmlComment() {
        return "<!-- " + MESSAGE + " -->";
    }

    public static String yamlComment() {
        return "# " + MESSAGE;
    }

    public static String sqlComment() {
        return "-- " + MESSAGE;
    }
}
