package dev.harpia.emit;

import dev.harpia.diag.DiagnosticCollector;
import dev.harpia.diag.ErrorCodes;
import dev.harpia.diag.SourceRef;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.TreeSet;
import java.util.stream.Stream;

/**
 * Synchronizes a generated tree with a directory on disk.
 *
 * <p>Harpia owns exactly the files listed in its manifest and nothing else. A file it did not
 * generate is never deleted, never overwritten silently and never assumed to be disposable: it is
 * reported and left alone. A file it generated before and no longer generates is stale, and is
 * removed only when {@code --clean} is requested.
 *
 * <p>Writing is idempotent. A file whose content is already identical is not rewritten, so build
 * timestamps stay meaningful and editors do not see phantom changes.
 */
public final class OutputWriter {

    /** Lists every file Harpia owns in this directory. It lives inside the output it describes. */
    public static final String MANIFEST = ".harpia-manifest";

    private OutputWriter() {
    }

    public static Optional<WriteReport> sync(
            Path projectRoot,
            String outputDirectory,
            GeneratedTree tree,
            boolean clean,
            boolean force,
            DiagnosticCollector diagnostics) {
        Objects.requireNonNull(projectRoot, "projectRoot");
        Objects.requireNonNull(outputDirectory, "outputDirectory");
        Objects.requireNonNull(tree, "tree");
        Objects.requireNonNull(diagnostics, "diagnostics");

        Path root = projectRoot.toAbsolutePath().normalize();
        Path output = root.resolve(outputDirectory).normalize();
        if (!output.startsWith(root) || output.equals(root)) {
            error(diagnostics, "output directory must stay inside the project root: "
                    + outputDirectory, ErrorCodes.IO_PATH_ESCAPE);
            return Optional.empty();
        }
        if (Files.isSymbolicLink(output)) {
            error(diagnostics, "output directory must not be a symbolic link: " + outputDirectory,
                    ErrorCodes.IO_PATH_ESCAPE);
            return Optional.empty();
        }
        if (Files.exists(output) && !Files.isDirectory(output)) {
            error(diagnostics, "output path exists and is not a directory: " + outputDirectory,
                    ErrorCodes.IO_FAILURE);
            return Optional.empty();
        }

        try {
            return Optional.of(write(output, tree, clean, force, diagnostics));
        } catch (Blocked blocked) {
            return Optional.empty();
        } catch (IOException | UncheckedIOException exception) {
            error(diagnostics, "failed to write " + outputDirectory + ": " + exception.getMessage(),
                    ErrorCodes.IO_FAILURE);
            return Optional.empty();
        }
    }

    private static WriteReport write(
            Path output,
            GeneratedTree tree,
            boolean clean,
            boolean force,
            DiagnosticCollector diagnostics) throws IOException {
        TreeSet<String> previous = readManifest(output);
        TreeSet<String> generated = new TreeSet<>(tree.files().keySet());
        TreeSet<String> present = existingFiles(output);

        TreeSet<String> stale = new TreeSet<>(previous);
        stale.removeAll(generated);
        stale.retainAll(present);

        TreeSet<String> unknown = new TreeSet<>(present);
        unknown.removeAll(generated);
        unknown.removeAll(previous);

        for (String file : unknown) {
            diagnostics.warning(
                    ErrorCodes.IO_UNKNOWN_OUTPUT_FILE,
                    "'" + file + "' was not generated by Harpia and is never deleted",
                    SourceRef.file(relative(output, file)));
        }
        if (clean && !unknown.isEmpty() && !force) {
            diagnostics.error(
                    ErrorCodes.IO_CLEAN_BLOCKED,
                    "--clean found " + unknown.size()
                            + " file(s) Harpia does not own; re-run with --force to clean anyway",
                    SourceRef.file(output.getFileName().toString()));
            throw new Blocked();
        }

        List<String> created = new ArrayList<>();
        List<String> updated = new ArrayList<>();
        List<String> unchanged = new ArrayList<>();
        Files.createDirectories(output);
        for (Map.Entry<String, String> file : tree.files().entrySet()) {
            Path path = resolve(output, file.getKey());
            if (Files.isSymbolicLink(path)) {
                error(diagnostics, "refusing to write through a symbolic link: " + file.getKey(),
                        ErrorCodes.IO_PATH_ESCAPE);
                throw new Blocked();
            }
            if (Files.exists(path)
                    && Files.readString(path, StandardCharsets.UTF_8).equals(file.getValue())) {
                unchanged.add(file.getKey());
                continue;
            }
            boolean existed = Files.exists(path);
            Files.createDirectories(path.getParent());
            Files.writeString(path, file.getValue(), StandardCharsets.UTF_8);
            (existed ? updated : created).add(file.getKey());
        }

        List<String> deleted = new ArrayList<>();
        if (clean) {
            for (String file : stale) {
                Files.deleteIfExists(resolve(output, file));
                deleted.add(file);
            }
            pruneEmptyDirectories(output);
        }

        // Harpia keeps owning a stale file until it actually removes it. Dropping it from the
        // manifest now would turn it into an unknown file that --clean could never touch again.
        TreeSet<String> owned = new TreeSet<>(generated);
        owned.addAll(stale);
        deleted.forEach(owned::remove);
        writeManifest(output, owned);
        return new WriteReport(
                created, updated, unchanged, List.copyOf(stale), deleted, List.copyOf(unknown));
    }

    private static TreeSet<String> readManifest(Path output) throws IOException {
        Path manifest = output.resolve(MANIFEST);
        if (!Files.isRegularFile(manifest)) {
            return new TreeSet<>();
        }
        TreeSet<String> files = new TreeSet<>();
        for (String line : Files.readAllLines(manifest, StandardCharsets.UTF_8)) {
            String entry = line.strip();
            if (!entry.isEmpty() && !entry.startsWith("#")) {
                files.add(entry);
            }
        }
        return files;
    }

    private static void writeManifest(Path output, TreeSet<String> files) throws IOException {
        StringBuilder content = new StringBuilder(GeneratedHeader.yamlComment()).append('\n');
        files.forEach(file -> content.append(file).append('\n'));
        Files.writeString(output.resolve(MANIFEST), content.toString(), StandardCharsets.UTF_8);
    }

    private static TreeSet<String> existingFiles(Path output) throws IOException {
        if (!Files.isDirectory(output)) {
            return new TreeSet<>();
        }
        try (Stream<Path> files = Files.walk(output)) {
            TreeSet<String> result = new TreeSet<>();
            files.filter(Files::isRegularFile)
                    .map(path -> output.relativize(path).toString().replace('\\', '/'))
                    .filter(path -> !path.equals(MANIFEST))
                    .forEach(result::add);
            return result;
        }
    }

    /** Removes directories that became empty after a clean, never the output root itself. */
    private static void pruneEmptyDirectories(Path output) throws IOException {
        List<Path> directories;
        try (Stream<Path> paths = Files.walk(output)) {
            directories = paths.filter(Files::isDirectory)
                    .filter(path -> !path.equals(output))
                    .sorted(Comparator.comparingInt(Path::getNameCount).reversed())
                    .toList();
        }
        for (Path directory : directories) {
            try (Stream<Path> children = Files.list(directory)) {
                if (children.findAny().isEmpty()) {
                    Files.delete(directory);
                }
            }
        }
    }

    private static Path resolve(Path output, String relativePath) {
        Path path = output.resolve(relativePath).normalize();
        if (!path.startsWith(output)) {
            throw new IllegalArgumentException("generated path escapes the output directory: "
                    + relativePath);
        }
        return path;
    }

    private static String relative(Path output, String file) {
        return output.getFileName() + "/" + file;
    }

    private static void error(DiagnosticCollector diagnostics, String message, String code) {
        diagnostics.error(code, message, SourceRef.file("harpia.yaml"));
    }

    /** Signals that writing stopped after a diagnostic was already reported. */
    private static final class Blocked extends RuntimeException {

        private Blocked() {
            super(null, null, false, false);
        }
    }
}
