// Generated by Harpia. Do not edit.
package com.example.customer.repository;

import com.example.customer.domain.Customer;
import java.util.UUID;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Persistence port generated from the Harpia entity Customer.
 */
public interface CustomerRepository extends JpaRepository<Customer, UUID> {
}
