// Generated by Harpia. Do not edit.
package com.example.customer.error;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.ConstraintViolationException;
import java.util.stream.Collectors;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

/**
 * Maps the failures declared in the specification to their declared HTTP status.
 */
@RestControllerAdvice
public class ApiExceptionHandler {

    @ExceptionHandler(NotFoundException.class)
    public ResponseEntity<ApiError> notFound(NotFoundException exception) {
        return ResponseEntity.status(404)
                .body(new ApiError(404, "not found", exception.getMessage()));
    }

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ApiError> invalidInput(MethodArgumentNotValidException exception) {
        String message = exception.getBindingResult().getFieldErrors().stream()
                .map(error -> error.getField() + " " + error.getDefaultMessage())
                .sorted()
                .collect(Collectors.joining(", "));
        return ResponseEntity.status(400)
                .body(new ApiError(400, "invalid input", message));
    }

    @ExceptionHandler(ConstraintViolationException.class)
    public ResponseEntity<ApiError> invalidParameter(ConstraintViolationException exception) {
        String message = exception.getConstraintViolations().stream()
                .map(violation -> field(violation) + " " + violation.getMessage())
                .sorted()
                .collect(Collectors.joining(", "));
        return ResponseEntity.status(400)
                .body(new ApiError(400, "invalid input", message));
    }

    @ExceptionHandler(DataIntegrityViolationException.class)
    public ResponseEntity<ApiError> duplicate(DataIntegrityViolationException exception) {
        String cause = exception.getMostSpecificCause().getMessage();
        String field = "resource";
        if (cause != null) {
            if (cause.contains("uq_customer_email")) {
                field = "email";
            }
        }
        return ResponseEntity.status(409)
                .body(new ApiError(409, "duplicate", field + " already exists"));
    }

    private static String field(ConstraintViolation<?> violation) {
        String path = violation.getPropertyPath().toString();
        int last = path.lastIndexOf('.');
        return last < 0 ? path : path.substring(last + 1);
    }
}
