// Generated by Harpia. Do not edit.
package com.example.customer.error;

/**
 * Error body shared by every failure the specification declares.
 */
public record ApiError(
        int status,
        String error,
        String message) {
}
