// Generated by Harpia. Do not edit.
package com.example.customer.error;

/**
 * Raised when a Harpia `load ... by id` finds nothing.
 */
public class NotFoundException extends RuntimeException {

    private static final long serialVersionUID = 1L;

    public NotFoundException(String type, Object id) {
        super(type + " " + id + " was not found");
    }
}
