// Generated by Harpia. Do not edit.
package com.example.customer.service;

import com.example.customer.domain.Customer;
import com.example.customer.dto.CreateCustomerRequest;
import com.example.customer.dto.CustomerResponse;
import com.example.customer.dto.UpdateCustomerRequest;
import com.example.customer.error.NotFoundException;
import com.example.customer.repository.CustomerRepository;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.assertj.core.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.ArgumentMatchers;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.Mockito;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Sort;

/**
 * Every Harpia flow of Customer, observed against a mocked repository.
 */
@ExtendWith(MockitoExtension.class)
class CustomerServiceTest {

    private static final UUID ID = UUID.fromString("00000000-0000-0000-0000-000000000001");

    @Mock
    private CustomerRepository repository;

    @InjectMocks
    private CustomerService service;

    @Test
    void createCustomerPersistsWhatTheRequestCarries() {
        Mockito.when(repository.save(ArgumentMatchers.any(Customer.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        CreateCustomerRequest request = new CreateCustomerRequest("name", "email@example.com");

        CustomerResponse response = service.createCustomer(request);

        ArgumentCaptor<Customer> saved = ArgumentCaptor.forClass(Customer.class);
        Mockito.verify(repository).save(saved.capture());
        Assertions.assertThat(saved.getValue().getName()).isEqualTo(request.name());
        Assertions.assertThat(saved.getValue().getEmail()).isEqualTo(request.email());
        Assertions.assertThat(response.name()).isEqualTo(request.name());
    }

    @Test
    void getCustomerReturnsTheStoredRecord() {
        Customer entity = sampleEntity();
        Mockito.when(repository.findById(ID)).thenReturn(Optional.of(entity));

        CustomerResponse response = service.getCustomer(ID);

        Assertions.assertThat(response.id()).isEqualTo(entity.getId());
    }

    @Test
    void getCustomerFailsWhenNothingIsStored() {
        Mockito.when(repository.findById(ID)).thenReturn(Optional.empty());

        Assertions.assertThatThrownBy(() -> service.getCustomer(ID))
                .isInstanceOf(NotFoundException.class);
    }

    @Test
    void listCustomersReturnsEveryRecordInDeclaredOrder() {
        Customer entity = sampleEntity();
        Mockito.when(repository.findAll(ArgumentMatchers.any(Sort.class)))
                .thenReturn(List.of(entity));

        List<CustomerResponse> response = service.listCustomers();

        Assertions.assertThat(response).hasSize(1);
        ArgumentCaptor<Sort> order = ArgumentCaptor.forClass(Sort.class);
        Mockito.verify(repository).findAll(order.capture());
        Assertions.assertThat(order.getValue()).as("Harpia requires a stable order").isEqualTo(Sort.by("id"));
    }

    @Test
    void updateCustomerCopiesTheRequestOntoTheStoredRecord() {
        Customer entity = sampleEntity();
        Mockito.when(repository.findById(ID)).thenReturn(Optional.of(entity));
        Mockito.when(repository.save(ArgumentMatchers.any(Customer.class)))
                .thenAnswer(invocation -> invocation.getArgument(0));

        UpdateCustomerRequest request = new UpdateCustomerRequest("name", "email@example.com", true);

        CustomerResponse response = service.updateCustomer(ID, request);

        Assertions.assertThat(entity.getName()).isEqualTo(request.name());
        Assertions.assertThat(entity.getEmail()).isEqualTo(request.email());
        Assertions.assertThat(entity.getActive()).isEqualTo(request.active());
        Mockito.verify(repository).save(entity);
    }

    @Test
    void updateCustomerFailsWhenNothingIsStored() {
        Mockito.when(repository.findById(ID)).thenReturn(Optional.empty());

        UpdateCustomerRequest request = new UpdateCustomerRequest("name", "email@example.com", true);
        Assertions.assertThatThrownBy(() -> service.updateCustomer(ID, request))
                .isInstanceOf(NotFoundException.class);
    }

    @Test
    void deleteCustomerRemovesTheStoredRecord() {
        Customer entity = sampleEntity();
        Mockito.when(repository.findById(ID)).thenReturn(Optional.of(entity));

        service.deleteCustomer(ID);

        Mockito.verify(repository).delete(entity);
    }

    @Test
    void deleteCustomerFailsWhenNothingIsStored() {
        Mockito.when(repository.findById(ID)).thenReturn(Optional.empty());

        Assertions.assertThatThrownBy(() -> service.deleteCustomer(ID))
                .isInstanceOf(NotFoundException.class);
    }

    private static Customer sampleEntity() {
        Customer entity = new Customer();
        entity.setId(UUID.fromString("00000000-0000-0000-0000-000000000001"));
        entity.setName("name");
        entity.setEmail("email@example.com");
        entity.setActive(true);
        return entity;
    }
}
