-- Generated by Harpia. Do not edit.

CREATE TABLE customer (
    id uuid NOT NULL,
    name varchar(255) NOT NULL,
    email varchar(320) NOT NULL,
    active boolean NOT NULL,
    CONSTRAINT pk_customer PRIMARY KEY (id),
    CONSTRAINT uq_customer_email UNIQUE (email)
);
