// Generated by Harpia. Do not edit.
package com.example.customer.service;

import com.example.customer.domain.Customer;
import com.example.customer.dto.CreateCustomerRequest;
import com.example.customer.dto.CustomerResponse;
import com.example.customer.dto.UpdateCustomerRequest;
import com.example.customer.error.NotFoundException;
import com.example.customer.repository.CustomerRepository;
import java.util.List;
import java.util.UUID;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Application service generated from the Harpia use cases of Customer.
 */
@Service
public class CustomerService {

    private final CustomerRepository repository;

    public CustomerService(CustomerRepository repository) {
        this.repository = repository;
    }

    @Transactional
    public CustomerResponse createCustomer(CreateCustomerRequest request) {
        Customer customer = new Customer();
        customer.setName(request.name());
        customer.setEmail(request.email());
        customer = repository.save(customer);
        return toResponse(customer);
    }

    @Transactional(readOnly = true)
    public CustomerResponse getCustomer(UUID id) {
        Customer customer = repository.findById(id)
                .orElseThrow(() -> new NotFoundException("Customer", id));
        return toResponse(customer);
    }

    @Transactional(readOnly = true)
    public List<CustomerResponse> listCustomers() {
        List<Customer> customers = repository.findAll(Sort.by("id"));
        return customers.stream().map(CustomerService::toResponse).toList();
    }

    @Transactional
    public CustomerResponse updateCustomer(UUID id, UpdateCustomerRequest request) {
        Customer customer = repository.findById(id)
                .orElseThrow(() -> new NotFoundException("Customer", id));
        customer.setName(request.name());
        customer.setEmail(request.email());
        customer.setActive(request.active());
        customer = repository.save(customer);
        return toResponse(customer);
    }

    @Transactional
    public void deleteCustomer(UUID id) {
        Customer customer = repository.findById(id)
                .orElseThrow(() -> new NotFoundException("Customer", id));
        repository.delete(customer);
    }

    private static CustomerResponse toResponse(Customer entity) {
        return new CustomerResponse(
                entity.getId(),
                entity.getName(),
                entity.getEmail(),
                entity.getActive());
    }
}
