package dev.harpia.emit;

import static org.assertj.core.api.Assertions.assertThat;

import dev.harpia.diag.Diagnostic;
import dev.harpia.diag.DiagnosticCollector;
import dev.harpia.diag.ErrorCodes;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Optional;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Harpia owns exactly what its manifest lists. Everything else in the output directory belongs to
 * whoever put it there.
 */
class OutputWriterTest {

    @TempDir
    Path projectRoot;

    @Test
    void writesTheTreeAndRecordsWhatItOwns() {
        DiagnosticCollector diagnostics = new DiagnosticCollector();

        WriteReport report = sync(tree("pom.xml", "a", "src/App.java", "b"), false, false, diagnostics);

        assertThat(report.created()).containsExactly("pom.xml", "src/App.java");
        assertThat(report.written()).isEqualTo(2);
        assertThat(diagnostics.diagnostics()).isEmpty();
        assertThat(read("generated/pom.xml")).isEqualTo("a");
        assertThat(read("generated/" + OutputWriter.MANIFEST))
                .isEqualTo("# Generated by Harpia. Do not edit.\npom.xml\nsrc/App.java\n");
    }

    @Test
    void aSecondIdenticalBuildRewritesNothing() {
        sync(tree("pom.xml", "a"), false, false, new DiagnosticCollector());

        WriteReport report = sync(tree("pom.xml", "a"), false, false, new DiagnosticCollector());

        assertThat(report.unchanged()).containsExactly("pom.xml");
        assertThat(report.idempotent()).isTrue();
    }

    @Test
    void aChangedFileIsReportedAsUpdatedRatherThanCreated() {
        sync(tree("pom.xml", "a"), false, false, new DiagnosticCollector());

        WriteReport report = sync(tree("pom.xml", "b"), false, false, new DiagnosticCollector());

        assertThat(report.updated()).containsExactly("pom.xml");
        assertThat(read("generated/pom.xml")).isEqualTo("b");
    }

    @Test
    void aFileHarpiaNoLongerGeneratesIsStaleAndSurvivesWithoutClean() {
        sync(tree("pom.xml", "a", "old/Gone.java", "b"), false, false, new DiagnosticCollector());

        WriteReport report = sync(tree("pom.xml", "a"), false, false, new DiagnosticCollector());

        assertThat(report.stale()).containsExactly("old/Gone.java");
        assertThat(report.deleted()).isEmpty();
        assertThat(projectRoot.resolve("generated/old/Gone.java")).exists();
    }

    @Test
    void cleanRemovesStaleFilesAndTheDirectoriesTheyEmptied() {
        sync(tree("pom.xml", "a", "old/Gone.java", "b"), false, false, new DiagnosticCollector());

        WriteReport report = sync(tree("pom.xml", "a"), true, false, new DiagnosticCollector());

        assertThat(report.deleted()).containsExactly("old/Gone.java");
        assertThat(projectRoot.resolve("generated/old")).doesNotExist();
        assertThat(projectRoot.resolve("generated/pom.xml")).exists();
    }

    @Test
    void aStaleFileStaysOwnedUntilItIsActuallyRemoved() {
        sync(tree("pom.xml", "a", "old/Gone.java", "b"), false, false, new DiagnosticCollector());
        sync(tree("pom.xml", "a"), false, false, new DiagnosticCollector());

        WriteReport report = sync(tree("pom.xml", "a"), true, false, new DiagnosticCollector());

        assertThat(report.deleted())
                .as("a plain build must not make a stale file unreachable to --clean")
                .containsExactly("old/Gone.java");
        assertThat(report.unknown()).isEmpty();
        assertThat(projectRoot.resolve("generated/old/Gone.java")).doesNotExist();
        assertThat(read("generated/" + OutputWriter.MANIFEST))
                .isEqualTo("# Generated by Harpia. Do not edit.\npom.xml\n");
    }

    @Test
    void aFileHarpiaNeverGeneratedIsReportedAndNeverDeleted() throws IOException {
        sync(tree("pom.xml", "a"), false, false, new DiagnosticCollector());
        write("generated/notes.md", "mine");
        DiagnosticCollector diagnostics = new DiagnosticCollector();

        WriteReport report = sync(tree("pom.xml", "a"), true, true, diagnostics);

        assertThat(report.unknown()).containsExactly("notes.md");
        assertThat(report.deleted()).isEmpty();
        assertThat(projectRoot.resolve("generated/notes.md")).exists();
        assertThat(diagnostics.diagnostics())
                .singleElement()
                .satisfies(diagnostic -> {
                    assertThat(diagnostic.code()).isEqualTo(ErrorCodes.IO_UNKNOWN_OUTPUT_FILE);
                    assertThat(diagnostic.isError()).isFalse();
                });
    }

    @Test
    void cleanRefusesToRunWhileUnknownFilesArePresent() throws IOException {
        sync(tree("pom.xml", "a"), false, false, new DiagnosticCollector());
        write("generated/notes.md", "mine");
        DiagnosticCollector diagnostics = new DiagnosticCollector();

        Optional<WriteReport> report = OutputWriter.sync(
                projectRoot, "generated", tree("pom.xml", "a"), true, false, diagnostics);

        assertThat(report).isEmpty();
        assertThat(diagnostics.diagnostics())
                .extracting(Diagnostic::code)
                .contains(ErrorCodes.IO_CLEAN_BLOCKED);
        assertThat(projectRoot.resolve("generated/notes.md")).exists();
    }

    @Test
    void refusesAnOutputDirectoryOutsideTheProject() {
        DiagnosticCollector diagnostics = new DiagnosticCollector();

        Optional<WriteReport> report = OutputWriter.sync(
                projectRoot, "../escape", tree("pom.xml", "a"), false, false, diagnostics);

        assertThat(report).isEmpty();
        assertThat(diagnostics.diagnostics())
                .extracting(Diagnostic::code)
                .containsExactly(ErrorCodes.IO_PATH_ESCAPE);
    }

    @Test
    void refusesToWriteThroughASymbolicLink() throws IOException {
        Path outside = Files.createDirectory(projectRoot.resolve("outside"));
        Files.createDirectories(projectRoot.resolve("generated"));
        Files.createSymbolicLink(
                projectRoot.resolve("generated/pom.xml"),
                Files.writeString(outside.resolve("real.xml"), "x", StandardCharsets.UTF_8));
        DiagnosticCollector diagnostics = new DiagnosticCollector();

        Optional<WriteReport> report = OutputWriter.sync(
                projectRoot, "generated", tree("pom.xml", "a"), false, false, diagnostics);

        assertThat(report).isEmpty();
        assertThat(diagnostics.diagnostics())
                .extracting(Diagnostic::code)
                .contains(ErrorCodes.IO_PATH_ESCAPE);
        assertThat(Files.readString(outside.resolve("real.xml"), StandardCharsets.UTF_8))
                .isEqualTo("x");
    }

    private WriteReport sync(
            GeneratedTree tree, boolean clean, boolean force, DiagnosticCollector diagnostics) {
        return OutputWriter.sync(projectRoot, "generated", tree, clean, force, diagnostics)
                .orElseThrow();
    }

    private static GeneratedTree tree(String... pathsAndContents) {
        GeneratedTree tree = new GeneratedTree();
        for (int index = 0; index < pathsAndContents.length; index += 2) {
            tree.put(pathsAndContents[index], pathsAndContents[index + 1]);
        }
        return tree;
    }

    private void write(String relativePath, String content) throws IOException {
        Path path = projectRoot.resolve(relativePath);
        Files.createDirectories(path.getParent());
        Files.writeString(path, content, StandardCharsets.UTF_8);
    }

    private String read(String relativePath) {
        try {
            return Files.readString(projectRoot.resolve(relativePath), StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new java.io.UncheckedIOException(exception);
        }
    }
}
