package dev.harpia;

import static org.assertj.core.api.Assertions.assertThat;

import dev.harpia.diag.DiagnosticCollector;
import dev.harpia.emit.OutputWriter;
import dev.harpia.emit.WriteReport;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Comparator;
import java.util.HexFormat;
import java.util.List;
import java.util.stream.Stream;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

/**
 * Determinism where the user actually sees it: bytes on disk.
 *
 * <p>{@link DeterminismTest} hashes trees in memory, which proves the compiler is a function. It
 * cannot prove that synchronizing that tree with a directory converges — writing is stateful, it
 * consults a manifest, and it deletes. A directory rebuilt over an old build has to end up
 * byte-identical to one built into nothing, or "regenerate at any time" is not a property Harpia
 * has.
 */
class RebuildEqualityTest {

    private static final String OUTPUT = "generated";

    @TempDir
    Path projectRoot;

    @BeforeEach
    void copyExample() throws IOException {
        copyTree(Path.of("examples/customer"), projectRoot);
    }

    @Test
    void aCleanRebuildOverAnOldBuildEqualsABuildIntoNothing() throws IOException {
        build(false);
        String fromNothing = hashOutput();

        // A build of an older specification left a file the current one does not generate.
        Path stale = projectRoot.resolve(OUTPUT)
                .resolve("src/main/java/com/example/customer/domain/Order.java");
        Files.writeString(stale, "// generated by an older specification\n", StandardCharsets.UTF_8);
        Files.writeString(
                projectRoot.resolve(OUTPUT).resolve(OutputWriter.MANIFEST),
                Files.readString(projectRoot.resolve(OUTPUT).resolve(OutputWriter.MANIFEST),
                                StandardCharsets.UTF_8)
                        + "src/main/java/com/example/customer/domain/Order.java\n",
                StandardCharsets.UTF_8);

        WriteReport report = build(true);

        assertThat(report.deleted())
                .containsExactly("src/main/java/com/example/customer/domain/Order.java");
        assertThat(hashOutput())
                .as("a cleaned rebuild must not remember the older build in any byte")
                .isEqualTo(fromNothing);
    }

    @Test
    void deletingTheOutputAndRebuildingReproducesEveryByte() throws IOException {
        build(false);
        String first = hashOutput();
        List<String> firstPaths = paths();

        deleteTree(projectRoot.resolve(OUTPUT));
        WriteReport report = build(false);

        assertThat(report.created()).isNotEmpty();
        assertThat(report.updated()).isEmpty();
        assertThat(paths()).isEqualTo(firstPaths);
        assertThat(hashOutput()).isEqualTo(first);
    }

    @Test
    void rebuildingOverAnIdenticalOutputTouchesNothing() throws IOException {
        build(false);
        String first = hashOutput();

        WriteReport report = build(true);

        assertThat(report.idempotent())
                .as("nothing changed, so nothing should be written: %s", report)
                .isTrue();
        assertThat(report.unknown()).isEmpty();
        assertThat(hashOutput()).isEqualTo(first);
    }

    private WriteReport build(boolean clean) {
        CompileResult result = new HarpiaCompiler().compile(
                new CompileRequest(projectRoot, CompileRequest.Mode.BUILD));
        assertThat(result.diagnostics()).isEmpty();

        DiagnosticCollector diagnostics = new DiagnosticCollector();
        WriteReport report = OutputWriter.sync(
                        projectRoot,
                        result.outputDirectory().orElseThrow(),
                        result.tree().orElseThrow(),
                        clean,
                        false,
                        diagnostics)
                .orElseThrow();
        assertThat(diagnostics.diagnostics()).isEmpty();
        return report;
    }

    /** Hashes every path and every byte under the output directory, manifest included. */
    private String hashOutput() throws IOException {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            Path output = projectRoot.resolve(OUTPUT);
            for (String path : paths()) {
                digest.update(path.getBytes(StandardCharsets.UTF_8));
                digest.update((byte) 0);
                digest.update(Files.readAllBytes(output.resolve(path)));
                digest.update((byte) 0);
            }
            return HexFormat.of().formatHex(digest.digest());
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException(exception);
        }
    }

    private List<String> paths() throws IOException {
        Path output = projectRoot.resolve(OUTPUT);
        try (Stream<Path> files = Files.walk(output)) {
            return files.filter(Files::isRegularFile)
                    .map(file -> output.relativize(file).toString())
                    .sorted()
                    .toList();
        }
    }

    /** Copies the specification inputs only: a previous build of the example is not an input. */
    private static void copyTree(Path from, Path to) throws IOException {
        try (Stream<Path> files = Files.walk(from)) {
            for (Path source : files.filter(Files::isRegularFile).toList()) {
                Path relative = from.relativize(source);
                if (relative.startsWith(OUTPUT)) {
                    continue;
                }
                Path destination = to.resolve(relative.toString());
                Files.createDirectories(destination.getParent());
                Files.copy(source, destination);
            }
        }
    }

    private static void deleteTree(Path root) throws IOException {
        try (Stream<Path> files = Files.walk(root)) {
            for (Path path : files.sorted(Comparator.reverseOrder()).toList()) {
                Files.delete(path);
            }
        }
    }
}
