// Generated by Harpia. Do not edit.
package com.example.customer.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;

/**
 * Request model generated from the input of Create Customer.
 */
public record CreateCustomerRequest(
        @NotBlank String name,
        @Email @NotBlank String email) {
}
