// Generated by Harpia. Do not edit.
package com.example.customer.dto;

import java.util.UUID;

/**
 * Response model generated from the Harpia entity Customer.
 */
public record CustomerResponse(
        UUID id,
        String name,
        String email,
        Boolean active) {
}
