// Generated by Harpia. Do not edit.
package com.example.customer.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;

/**
 * Request model generated from the input of Update Customer.
 */
public record UpdateCustomerRequest(
        @NotBlank String name,
        @Email @NotBlank String email,
        @NotNull Boolean active) {
}
